### ISSUE TITLE
JRuby 9.0.5: wrong number of arguments calling `alias_method` 

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-doctest#15]
stack trace:

```
ArgumentError: wrong number of arguments calling `alias_method` (0 for 2)
/home/travis/.rvm/gems/jruby-9.0.5.0/bundler/gems/asciidoctor-doctest-13569fe28d36/lib/asciidoctor/doctest/asciidoc_converter.rb:81:in `<class:AsciidocConverter>'
/home/travis/.rvm/gems/jruby-9.0.5.0/bundler/gems/asciidoctor-doctest-13569fe28d36/lib/asciidoctor/doctest/asciidoc_converter.rb:13:in `<module:DocTest>'
/home/travis/.rvm/gems/jruby-9.0.5.0/bundler/gems/asciidoctor-doctest-13569fe28d36/lib/asciidoctor/doctest/asciidoc_converter.rb:9:in `<module:Asciidoctor>'
/home/travis/.rvm/gems/jruby-9.0.5.0/bundler/gems/asciidoctor-doctest-13569fe28d36/lib/asciidoctor/doctest/asciidoc_converter.rb:8:in `<top>'
/home/travis/.rvm/gems/jruby-9.0.5.0/bundler/gems/asciidoctor-doctest-13569fe28d36/lib/asciidoctor/doctest/rake_tasks.rb:1:in `<top>'
/home/travis/.rvm/gems/jruby-9.0.5.0/bundler/gems/asciidoctor-doctest-13569fe28d36/lib/asciidoctor/doctest/rake_tasks.rb:1:in `<top>'
/home/travis/.rvm/gems/jruby-9.0.5.0/bundler/gems/asciidoctor-doctest-13569fe28d36/lib/asciidoctor/doctest.rb:1:in `<top>'
/home/travis/.rvm/gems/jruby-9.0.5.0/bundler/gems/asciidoctor-doctest-13569fe28d36/lib/asciidoctor/doctest.rb:23:in `(root)'
/home/travis/build/asciidoctor/asciidoctor-reveal.js/Rakefile:1:in `(root)'
/home/travis/build/asciidoctor/asciidoctor-reveal.js/Rakefile:1:in `block in (root)'
/home/travis/.rvm/gems/jruby-9.0.5.0/bin/jruby_executable_hooks:15:in `<top>'
(See full trace by running task with --trace)
```

Travis CI job: https://travis-ci.org/asciidoctor/asciidoctor-reveal.js/jobs/266563533

Works fine on JRuby 9.1.12. I'm not familiar with JRuby's versioning but if it's ancient, I don't mind dropping my testing of that platform.

**Comment by jirutka** [comment]
This looks like some weird bug in JRuby 9.0.5; there’s no occurrence of `alias_method` called without arguments in DocTest. JRuby 9.0.5 is quite (30 Jan 2016) and not supported by upstream as I know. The latest version is 9.1.12.0.

Please drop 9.0.5 from the build matrix, it doesn’t make much sense to support this version.
